#ifndef CHINESE_INPUT_AGENT_UI_IDS_H
#define CHINESE_INPUT_AGENT_UI_IDS_H

/* Control IDs are scoped by top-level window; installer IDs intentionally reuse the same numeric range. */

/* Main window controls. */
#define IDC_TEXTBOX 1001
#define IDC_ENCRYPT 1002
#define IDC_DECRYPT 1003
#define IDC_CLEAR 1004
#define IDC_KEY_SELECT 1006
#define IDC_KEY_TRANSFER 1007
#define IDC_TOPIC 1008
#define IDC_TEXT_OVERLAY 1009
#define IDC_KEY_TRANSFER_GROUP 1010
#define IDC_KEY_TRANSFER_PRIVATE 1011
#define IDC_KEY_AUX 1012
#define IDC_GENERATION_SETTINGS 1013

/* Generation settings controls. */
#define IDC_GEN_PROMPT_EDIT 2001
#define IDC_GEN_TEMP_SLIDER 2002
#define IDC_GEN_TEMP_VALUE 2003
#define IDC_GEN_TOPP_SLIDER 2004
#define IDC_GEN_TOPP_VALUE 2005
#define IDC_GEN_REDUNDANCY 2006
#define IDC_GEN_SAVE_CONFIG 2007

/* Name prompt controls. */
#define IDC_NAME_EDIT 3001

/* Key transfer window controls. */
#define IDC_KEY_TEXT 3002
#define IDC_KEY_IMPORT 3003
#define IDC_KEY_EXPORT 3004
#define IDC_KEY_OVERLAY 3005
#define IDC_GROUP_NAME 3006
#define IDC_GROUP_CREATE 3007
#define IDC_GROUP_REKEY 3008
#define IDC_GROUP_SELF_NAME 3009
#define IDC_GROUP_MEMBER_ID 3010
#define IDC_GROUP_MEMBER_ALIAS 3011
#define IDC_GROUP_SET_ALIAS 3012

/* Installer window controls. */
#define IDC_INSTALLER_PATH_EDIT 1001
#define IDC_INSTALLER_BROWSE 1002
#define IDC_INSTALLER_INSTALL 1003
#define IDC_INSTALLER_CLOSE 1004
#define IDC_INSTALLER_LAUNCH 1005
#define IDC_INSTALLER_PROGRESS 1006
#define IDC_INSTALLER_STATUS 1007

#endif
