#ifndef CHINESE_INPUT_AGENT_UI_LAYOUT_H
#define CHINESE_INPUT_AGENT_UI_LAYOUT_H

#define UI_MAIN_MARGIN 12
#define UI_MAIN_GAP 8
#define UI_MAIN_COMBO_HEIGHT 30
#define UI_MAIN_TOPIC_HEIGHT 30
#define UI_MAIN_BUTTON_HEIGHT 38
#define UI_MAIN_CUSTOM_BUTTON_WIDTH 78
#define UI_MAIN_MIN_EDIT_HEIGHT 80
#define UI_MAIN_MIN_BUTTON_WIDTH 58
#define UI_MAIN_COMBO_DROPDOWN_HEIGHT 220
#define UI_MAIN_MIN_TRACK_WIDTH 620
#define UI_MAIN_MIN_TRACK_HEIGHT 360
#define UI_MAIN_INITIAL_WIDTH 760
#define UI_MAIN_INITIAL_HEIGHT 520

#define UI_KEY_TRANSFER_MARGIN 12
#define UI_KEY_TRANSFER_GAP 8
#define UI_KEY_TRANSFER_BUTTON_HEIGHT 36
#define UI_KEY_TRANSFER_BUTTON_WIDTH 110
#define UI_KEY_TRANSFER_MIN_EDIT_HEIGHT 80
#define UI_KEY_TRANSFER_MIN_TRACK_WIDTH 480
#define UI_KEY_TRANSFER_MIN_TRACK_HEIGHT 380
#define UI_KEY_TRANSFER_INITIAL_WIDTH 620
#define UI_KEY_TRANSFER_INITIAL_HEIGHT 500

#define UI_NAME_LABEL_X 14
#define UI_NAME_LABEL_Y 16
#define UI_NAME_LABEL_WIDTH 260
#define UI_NAME_LABEL_HEIGHT 24
#define UI_NAME_EDIT_X 14
#define UI_NAME_EDIT_Y 46
#define UI_NAME_EDIT_WIDTH 300
#define UI_NAME_EDIT_HEIGHT 28
#define UI_NAME_OK_X 146
#define UI_NAME_CANCEL_X 234
#define UI_NAME_BUTTON_Y 88
#define UI_NAME_BUTTON_WIDTH 80
#define UI_NAME_BUTTON_HEIGHT 32
#define UI_NAME_WINDOW_WIDTH 350
#define UI_NAME_WINDOW_HEIGHT 170

#define UI_GEN_MARGIN 12
#define UI_GEN_GAP 8
#define UI_GEN_LABEL_HEIGHT 22
#define UI_GEN_EDIT_HEIGHT 230
#define UI_GEN_SLIDER_HEIGHT 32
#define UI_GEN_BUTTON_WIDTH 86
#define UI_GEN_BUTTON_HEIGHT 32
#define UI_GEN_WINDOW_WIDTH 620
#define UI_GEN_WINDOW_HEIGHT 520

#define UI_OVERLAY_INSET 8
#define UI_OVERLAY_TOTAL_INSET (UI_OVERLAY_INSET * 2)
#define UI_OVERLAY_TEXT_RGB 128
#define UI_OVERLAY_TRANSIENT_CLEAR_MS 4500

#define UI_FONT_FALLBACK_HEIGHT -16

#endif
